-- =====================================================
-- Product Management System - MySQL schema + sample data
-- Run this file once to create everything.
-- =====================================================
CREATE DATABASE IF NOT EXISTS product_management CHARACTER SET utf8mb4;
USE product_management;

-- ---------- Tables ----------
CREATE TABLE IF NOT EXISTS Categories (
  Id       INT AUTO_INCREMENT PRIMARY KEY,
  Name     VARCHAR(100) NOT NULL,
  IsActive TINYINT(1)   NOT NULL DEFAULT 1,
  UNIQUE KEY IX_Categories_Name (Name)
);

CREATE TABLE IF NOT EXISTS Products (
  Id            INT AUTO_INCREMENT PRIMARY KEY,
  Name          VARCHAR(150)  NOT NULL,
  Sku           VARCHAR(50)   NOT NULL,
  CategoryId    INT           NOT NULL,
  Price         DECIMAL(12,2) NOT NULL,
  StockQuantity INT           NOT NULL DEFAULT 0,
  Description   LONGTEXT      NULL,
  ImageUrl      VARCHAR(255)  NULL,
  IsActive      TINYINT(1)    NOT NULL DEFAULT 1,
  CreatedAt     DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UpdatedAt     DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY IX_Products_Sku (Sku),
  KEY IX_Products_CategoryId (CategoryId),
  CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId)
    REFERENCES Categories(Id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Sales (
  Id        INT AUTO_INCREMENT PRIMARY KEY,
  ProductId INT           NOT NULL,
  Quantity  INT           NOT NULL,
  UnitPrice DECIMAL(12,2) NOT NULL,
  SoldAt    DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY IX_Sales_ProductId (ProductId),
  CONSTRAINT FK_Sales_Products FOREIGN KEY (ProductId)
    REFERENCES Products(Id) ON DELETE CASCADE
);

-- Login accounts. The API creates the default admin (admin / Admin@123)
-- automatically on first run, because the password hash is generated by the app.
CREATE TABLE IF NOT EXISTS Users (
  Id           INT AUTO_INCREMENT PRIMARY KEY,
  Username     VARCHAR(50)  NOT NULL,
  PasswordHash VARCHAR(255) NOT NULL,
  FullName     VARCHAR(100) NOT NULL,
  Role         VARCHAR(30)  NOT NULL DEFAULT 'Admin',
  UNIQUE KEY IX_Users_Username (Username)
);

-- ---------- Sample data ----------
INSERT INTO Categories (Name, IsActive) VALUES
  ('Electronics', 1), ('Accessories', 1), ('Furniture', 1), ('Clothing', 0), ('Home Appliances', 1);

INSERT INTO Products (Name, Sku, CategoryId, Price, StockQuantity, Description) VALUES
  ('Laptop Pro',      'L001', 1, 50000, 12, 'High-performance laptop with latest processor, 16GB RAM and 512GB SSD. Suitable for work and gaming.'),
  ('Wireless Mouse',  'M002', 2,   800, 35, 'High quality wireless mouse with ergonomic design.'),
  ('Gaming Keyboard', 'K003', 2,  1200,  0, 'Mechanical RGB gaming keyboard.'),
  ('Office Chair',    'C004', 3,  3500, 18, 'Comfortable ergonomic office chair.'),
  ('Headphones',      'H005', 2,  1800,  6, 'Over-ear headphones with deep bass.');

INSERT INTO Sales (ProductId, Quantity, UnitPrice, SoldAt) VALUES
  (1, 2, 50000, NOW() - INTERVAL 20 DAY),
  (2, 10,  800, NOW() - INTERVAL 12 DAY),
  (3, 5,  1200, NOW() - INTERVAL 8 DAY),
  (4, 3,  3500, NOW() - INTERVAL 3 DAY),
  (5, 4,  1800, NOW() - INTERVAL 1 DAY);
